# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Specify versions of Php & Dolibarr to test against
# DOL_VERSION   = Github Branch
# DATA_VERSION  = Demo data Versions tu USe for Testing
env:
    global:
        # Set to true for very verbose output
        - DEBUG=false  
        
matrix:
    include:
#        # Dolibarr V4.0 Branch       
#        - php: 5.6
#          env: DOL_VERSION=4.0 DATA_VERSION=4.0.0     
#        - php: 7.0
#          env: DOL_VERSION=4.0 DATA_VERSION=4.0.0  
#        - php: 7.1
#          env: DOL_VERSION=4.0 DATA_VERSION=4.0.0
#
#        # Dolibarr V5.0 Branch       
#        - php: 5.6
#          env: DOL_VERSION=5.0 DATA_VERSION=5.0.0     
#        - php: 7.0
#          env: DOL_VERSION=5.0 DATA_VERSION=5.0.0  
#        - php: 7.1
#          env: DOL_VERSION=5.0 DATA_VERSION=5.0.0
#
#        # Dolibarr V6.0 Branch       
#        - php: 5.6
#          env: DOL_VERSION=6.0 DATA_VERSION=6.0.0     
#        - php: 7.0
#          env: DOL_VERSION=6.0 DATA_VERSION=6.0.0     
#        - php: 7.1
#          env: DOL_VERSION=6.0 DATA_VERSION=6.0.0     
#        - php: 7.2
#          env: DOL_VERSION=6.0 DATA_VERSION=6.0.0     
#
#        # Dolibarr V7.0 Branch       
#        - php: 5.6
#          env: DOL_VERSION=7.0 DATA_VERSION=7.0.0     
        - php: 7.0
          env: DOL_VERSION=7.0 DATA_VERSION=7.0.0     
#        - php: 7.1
#          env: DOL_VERSION=7.0 DATA_VERSION=7.0.0     
#        - php: 7.2
#          env: DOL_VERSION=7.0 DATA_VERSION=7.0.0     
#          
#        # Dolibarr Develop Branch       
#        - php: 7.0
#          env: DOL_VERSION=develop DATA_VERSION=7.0.0     
#        - php: 7.1
#          env: DOL_VERSION=develop DATA_VERSION=7.0.0     
#        - php: 7.2
#          env: DOL_VERSION=develop DATA_VERSION=7.0.0     
          
    allow_failures:
        - env: DOL_VERSION=develop DATA_VERSION=7.0.0
          
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true
    
install:
    # Disable Xdebug ...
    - phpenv config-rm xdebug.ini
    - phpenv config-add build/x_memory.ini
    
before_script:
  
    - export DOL_BUILD_DIR=/tmp/Dolibarr
    - export PLUGIN_SLUG=$(basename $(pwd))
    
    - |
      echo Start travis
      echo Current dir is `pwd`
      echo Home dir is `echo ~`
      echo TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR
      echo DOL_BUILD_DIR is $DOL_BUILD_DIR
      echo PLUGIN_SLUG is $PLUGIN_SLUG
  
    - |
      if [ "$DEBUG" = true ]; then
        echo "Debugging informations"
        # Check PHP
        php -i
        # Check PHPUnit installation
        which phpunit
        phpunit --version
        # Check MySQL
        mysql --version
        mysql -e "SELECT VERSION();"
        echo
      fi
  
    # Clone Dolibarr & Move to Web folder
    - git clone --depth=1 --branch="$DOL_VERSION" https://github.com/Dolibarr/dolibarr.git $DOL_BUILD_DIR

    # Init Database
    - bash $TRAVIS_BUILD_DIR/build/install_database.sh
    
    # Setup Conf file
    - cd $DOL_BUILD_DIR
    - bash $TRAVIS_BUILD_DIR/build/configure_dolibarr.sh  
    - bash $TRAVIS_BUILD_DIR/build/upgrade_dolibarr.sh  
        
    # Copy Splash Module to Dolibarr folder
    - cp -rf "$TRAVIS_BUILD_DIR/.git"       "$DOL_BUILD_DIR/htdocs/.git"
    - cp -rf "$TRAVIS_BUILD_DIR/build"      "$DOL_BUILD_DIR/htdocs/build"
    - cp -rf "$TRAVIS_BUILD_DIR/splash"     "$DOL_BUILD_DIR/htdocs/splash"
    - cp "$TRAVIS_BUILD_DIR/.travis.yml"    "$DOL_BUILD_DIR/htdocs/.travis.yml"
    - cp "$TRAVIS_BUILD_DIR/grumphp.yml"    "$DOL_BUILD_DIR/htdocs/grumphp.yml"
    - cp "$TRAVIS_BUILD_DIR/composer.json"  "$DOL_BUILD_DIR/htdocs/composer.json"

    # Run Composer
    - cd "$DOL_BUILD_DIR/htdocs/"
    # With PHP 7 => Load Phpstan   
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require phpstan/phpstan-shim --no-update; fi
    - composer update 
    

    

script: 
    
    # Move to Dolibarr Root Dir
    - cd "$DOL_BUILD_DIR/htdocs"    
    
    # Run Grump Main Test Sequence
    - php ./splash/vendor/bin/grumphp run --testsuite=travis
    # With PHP 7 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then php ./splash/vendor/bin/grumphp run --testsuite=phpstan; fi     
    
    # Execute Bootstrap file    
    - php build/bootstrap.php
    # Show PhpUnit Version
    - phpunit --version
    # Run PhpUnit Main Sequence
    - phpunit -c build/phpunit.xml.dist 
    # Run PhpUnit Main Local Testsuite
    - phpunit -c build/phpunit.xml.dist --testsuite=Local
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
