# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Tell Travis CI we're using Cache
cache:
  directories:
    - $HOME/.composer/cache
    
# Specify versions of Php & Dolibarr to test against
# DOL   = Github Branch
# DATA  = Demo data Versions tu USe for Testing
matrix:
    include:
#        # Dolibarr V4.0 Branch       
#        - php: 5.6
#          env: DOL=4.0 DATA=4.0.0 STAN=0   
##        - php: 7.0
##          env: DOL=4.0 DATA=4.0.0 STAN=0
#        - php: 7.1
#          env: DOL=4.0 DATA=4.0.0 STAN=0
#
#        # Dolibarr V5.0 Branch       
#        - php: 5.6
#          env: DOL=5.0 DATA=5.0.0 STAN=0     
##        - php: 7.0
##          env: DOL=5.0 DATA=5.0.0 STAN=0  
        - php: 7.1
          env: DOL=5.0 DATA=5.0.0 STAN=0
#
#        # Dolibarr V6.0 Branch       
#        - php: 5.6
#          env: DOL=6.0 DATA=6.0.0 STAN=0    
##        - php: 7.0
##          env: DOL=6.0 DATA=6.0.0 STAN=1     
#        - php: 7.1
#          env: DOL=6.0 DATA=6.0.0 STAN=1     
##        - php: 7.2
##          env: DOL=6.0 DATA=6.0.0 STAN=1     
##
#        # Dolibarr V7.0 Branch       
#        - php: 5.6
#          env: DOL=7.0 DATA=7.0.0 STAN=0    
#        - php: 7.0
#          env: DOL=7.0 DATA=7.0.0 STAN=1       
##        - php: 7.1
##          env: DOL=7.0 DATA=7.0.0 STAN=1     
#        - php: 7.2
#          env: DOL=7.0 DATA=7.0.0 STAN=1     
#          
#        # Dolibarr V8.0 Branch       
#        - php: 5.6
#          env: DOL=8.0 DATA=7.0.0 STAN=0    
##        - php: 7.0
##          env: DOL=8.0 DATA=7.0.0 STAN=1       
#        - php: 7.1
#          env: DOL=8.0 DATA=7.0.0 STAN=1     
#        - php: 7.2
#          env: DOL=8.0 DATA=7.0.0 STAN=1     
#          
#        # Dolibarr Develop Branch       
#        - php: 5.6
#          env: DOL=develop DATA=7.0.0 STAN=0        
#        - php: 7.0
#          env: DOL=develop DATA=7.0.0 STAN=1    
##        - php: 7.1
##          env: DOL=develop DATA=7.0.0 STAN=1    
#        - php: 7.2
#          env: DOL=develop DATA=7.0.0 STAN=1    
#          
#    allow_failures:
#        - env: DOL=develop DATA=7.0.0 STAN=0 
#        - env: DOL=develop DATA=7.0.0 STAN=1    
          
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true
    
install:
    # Disable Xdebug ...
    - phpenv config-rm xdebug.ini
    - phpenv config-add build/x_memory.ini
    
before_script:
  
    - export DOL_BUILD_DIR=/tmp/Dolibarr
    - export PLUGIN_SLUG=$(basename $(pwd))
    
    - |
      echo Start travis
      echo Current dir is `pwd`
      echo Home dir is `echo ~`
      echo TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR
      echo DOL_BUILD_DIR is $DOL_BUILD_DIR
      echo PLUGIN_SLUG is $PLUGIN_SLUG
  
    # Clone Dolibarr & Move to Web folder
    - git clone --depth=1 --branch="$DOL" https://github.com/Dolibarr/dolibarr.git $DOL_BUILD_DIR

    # Init Database
    - bash $TRAVIS_BUILD_DIR/build/install_database.sh
    
    # Setup Conf file
    - cd $DOL_BUILD_DIR
    - bash $TRAVIS_BUILD_DIR/build/configure_dolibarr.sh  
    - bash $TRAVIS_BUILD_DIR/build/upgrade_dolibarr.sh  
        
    # Copy Splash Module to Dolibarr folder
    - cp -Rf $TRAVIS_BUILD_DIR/*            $DOL_BUILD_DIR/htdocs/custom/
    - cp -Rf $TRAVIS_BUILD_DIR/.git/        $DOL_BUILD_DIR/htdocs/custom/.git/
    - cp "$TRAVIS_BUILD_DIR/.travis.yml"    "$DOL_BUILD_DIR/htdocs/custom/.travis.yml"

    # Run Composer
    - cd "$DOL_BUILD_DIR/htdocs/custom/"
    # With PHP 7 => Load Phpstan   
    - if [[ $STAN == "1" ]]; then composer require phpstan/phpstan-shim 0.9.2 --no-update; fi
    - composer update 
    
script: 
    
    # Move to Dolibarr Root Dir
    - cd "$DOL_BUILD_DIR/htdocs/custom"    
    
    # Run Grump Main Test Sequence
    - php ./splash/vendor/bin/grumphp run --testsuite=travis
    # With PHP 7 => Execute Phpstan 
    - if [[ $STAN == "1" ]]; then php splash/vendor/bin/grumphp run --testsuite=phpstan; fi     
    
    # Execute Bootstrap file    
    - php build/bootstrap.php
    # Show PhpUnit Version
    - splash/vendor/phpunit/phpunit/phpunit --version
    # Run PhpUnit Main Sequence
    - splash/vendor/phpunit/phpunit/phpunit -c build/phpunit.xml.dist 
    # Run PhpUnit Main Local Testsuite
    - splash/vendor/phpunit/phpunit/phpunit -c build/phpunit.xml.dist --testsuite=Local
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
